name: lsrtcc_flutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter           

  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.2.0
  geolocator: ^5.3.1
  http: ^0.12.1
  flutter_spinkit: ^4.1.2+1
  # rflutter_alert: ^1.0.3
  emojis: ^0.8.1
  table_calendar: ^2.2.3
  # shared_preferences: ^0.5.12+4
  # intl: ^0.16.1
  date_time_format: ^1.0.0+4
  get: ^4.1.4
  get_storage: ^2.0.2
  path_provider: ^2.0.0
  date_format: ^2.0.2
  google_fonts: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
